### ISSUE TITLE
Problems installing CM01 - Install SQL Server 2019

### ISSUE THREAD

**Issue by timboo7** [DeploymentResearch/HydrationKitWS2022#10]
![image](https://user-images.githubusercontent.com/97058166/163011582-76f4d37c-26e2-4fbb-9bbd-09ddf3d092cf.png)

I have updated the following files 

ConfigurationFile.ini - line 147 with SQLSYSADMINACCOUNTS="TIMBO\Administrator" "BUILTIN\Administrators"

Install-HYDSQLServer2019.ps1 - line 133 with  $OriginalSQLSYSADMINACCOUNTS = "SQLSYSADMINACCOUNTS=`"TIMBO\Administrator`" `"BUILTIN\Administrators`"" 

Note that CU15 (SQLServer2019-KB5008996-x64.exe) is in the Updates folder

But there seems to be an error displayed as indicated in attachment

Any help, much appriechated 

Regards

Tim

**Comment by timboo7** [comment]
I think I have fixed this - it is because the $tsenv is not know at this point . Adding the $tsenv = New-Object -COMobject Microsoft.SMS.TSEnvironment line before it - fixes it (not elegant - but works)

**Comment by arwidmark** [comment]
Thanks for the info, I have updated the installation script with that change.

**Comment by timboo7** [comment]
No worries


Now I am having problems with SCCM 2111 - Single Site - OS deployment - not finding PS100003 (Configuration Manager Client Package) on the DP



This is before the TS starts



Have tried the following:-

Added Computer Account to Local Admins
Set the Network Access Account (to domain admin)


Any help would be much appreciated

Regards

Tim

**Comment by arwidmark** [comment]
That's one of the default packages. Verify that the DP role is happy, and then just run an Update Distribution Point on that package. I've seen it sometimes not being distributed by default.
