### ISSUE TITLE
Unable to install DC01

### ISSUE THREAD

**Issue by SAIYAN48** [DeploymentResearch/HydrationKitWS2022#14]
When the Deployment starts on VmWare the following errors occur:
![Untitled](https://user-images.githubusercontent.com/13972854/203223436-c19d98ca-eb4a-41e3-8dd2-6910deb626fb.png)

**Comment by arwidmark** [comment]
That' looks like a file missing in the media, it can't find the customsettings.ini file. Can you please drop a text file with a recursive file listing of the ISO file content. Here is a snippet that generates a listing (H: is the mounted ISO):

`Get-ChildItem -Path H:\ -Recurse | Select-Object FullName | Export-Csv -NoTypeInformation -Path C:\Temp\Files.csv`
