### ISSUE TITLE
Incorrect source path for Step 3.4

### ISSUE THREAD

**Issue by msmith719** [DeploymentResearch/HydrationKitWS2022#26]
Step 3.4 in the guide says "Copy the Windows ADK 11 WinPE Addon setup files (3 GB) to the following folder:
C:\CMLab\DS\Applications\Install - WinPE Addon for Windows ADK 11\Source". The correct path to place the files in is "C:\CMLab\DS\Applications\Install - Windows ADK 11 WinPE Addon\Source". The screenshot is correct, but the text is wrong.

**Comment by AndrewJNet** [comment]
Fixed! Thanks @msmith719
