### ISSUE TITLE
Incorrect source path for Step 3.5 and 3.6

### ISSUE THREAD

**Issue by msmith719** [DeploymentResearch/HydrationKitWS2022#27]
Steps 3.5 and 3.6 in the guide mention the path "C:\CMLab\DS\Applications\Install - SQL Server 2019\Source". The correct path based on the folder created by the script is "C:\CMLab\DS\Applications\Install - SQL Server 2019 Standard\Source". The screenshots are correct, but the text is wrong.

**Comment by AndrewJNet** [comment]
Fixed. Thanks again @msmith719
